<?php

use App\Supply;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
class SupplyTableSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		//delete users table records
		DB::table('supply')->delete();
		//insert some dummy records
		DB::table('supply')->insert([
			array( 'stocknumber' => '01-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'MTRS.','reorderpoint'=> '0','supplytype' => 'ACETATE, TRANSPARENT. 1.20 MTRS. MIN. WIDTH, 50/MTRS'),
			array( 'stocknumber' => '01-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'CANS','reorderpoint'=> '0','supplytype' => 'AIR FRESHNER '),
			array( 'stocknumber' => '01-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'BTL','reorderpoint'=> '0','supplytype' => 'ALCOHOL, RUBBING, 70%'),
			array( 'stocknumber' => '01-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'AUDIO CASSETTE TAPE BLANK ELECTRA 90 MIN'),
			array( 'stocknumber' => '01-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'AIRPOT, 4 LITERS '),
			array( 'stocknumber' => '02-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'BALLAST, 18 WATTS'),
			array( 'stocknumber' => '02-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'BALLAST, 36 WATTS'),
			array( 'stocknumber' => '02-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'BALLAST, 40 WATTS'),
			array( 'stocknumber' => '02-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'BALLPEN FINE POINT BLACK'),
			array( 'stocknumber' => '02-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'BALLPEN FINE POINT BLUE '),
			array( 'stocknumber' => '02-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'BALLPEN FINE POINT RED'),
			array( 'stocknumber' => '02-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'BATTERY (AA) '),
			array( 'stocknumber' => '02-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'BATTERY (AAA)'),
			array( 'stocknumber' => '02-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'BINDER, TB, "11 x 14-7/8"'),
			array( 'stocknumber' => '02-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'BATTERY D, 1.5 BOLTS 2 PCS/PACK'),
			array( 'stocknumber' => '03-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CALCULATOR, SCIENTIFIC, 10 + 2 DIGITS CAP. DOT MATRIX, TWO WAY(SOLAR/CELL TYPE) ADRITE BRAND'),
			array( 'stocknumber' => '03-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PACK','reorderpoint'=> '0','supplytype' => 'CARBON PAPER, LONG, 100/BXS'),
			array( 'stocknumber' => '03-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'CARTOLINA, ASSORTED '),
			array( 'stocknumber' => '03-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '03-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CHALK WHITE DUSTLESS, DURA SMOOTH, 100/BXS '),
			array( 'stocknumber' => '03-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'CLIP PAPER, GEM TYPE 32MM (1¼), VINYL COATED, 100/BOX RAINBOW'),
			array( 'stocknumber' => '03-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'CLIP PAPER, GEM TYPE 50MM (2), VINYL COATED, 100/BOX RAINBOW'),
			array( 'stocknumber' => '03-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'CLIP, BACKFOLD, 19MM (¾) ( ALL METAL, 12PCS/BOX'),
			array( 'stocknumber' => '03-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'CLIP, BACKFOLD, 25MM(1)  ALL METAL, 12PCS/BOX'),
			array( 'stocknumber' => '03-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'COLUMNAR 6 COLUMS                                                           '),
			array( 'stocknumber' => '03-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPACT DISC. REWRITABLE (CD-RW) 700MB MINS CAP. 80MINS REC.'),
			array( 'stocknumber' => '03-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '03-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 1 PLY, PLAIN , 11" X 14-7/8'),
			array( 'stocknumber' => '03-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 1 PLY, PLAIN , 11" X 9-1/2'),
			array( 'stocknumber' => '03-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 1 PLY, PLAIN , 3-2/3 X 8'),
			array( 'stocknumber' => '03-016','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 2  PLY, PLAIN , 11" X 9-1/2'),
			array( 'stocknumber' => '03-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 2 PLY, PLAIN , 11" X 14-7/8'),
			array( 'stocknumber' => '03-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 3  PLY, PLAIN , 11" X 9-1/2'),
			array( 'stocknumber' => '03-019','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'COMPUTER FORMS, 3 PLY, PLAIN , 11" X 14--7/8"'),
			array( 'stocknumber' => '03-020','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CORRECTION FLUID WATER BASE 15 ML'),
			array( 'stocknumber' => '03-021','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CORRECTION TAPE, DISPOSABLE, USABLE LENGTH OF 6MTRS. THICKNESS  '),
			array( 'stocknumber' => '03-022','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'CUTTER BLADE, HEAVY DUTY 18MM WIDTH, 10PCS/TUBE '),
			array( 'stocknumber' => '03-023','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CUTTER, GEN. PURPOSE, HEAVY DUTY BUILT-IN W/ METAL SLIDING GUIDE W/ SCREW'),
			array( 'stocknumber' => '03-024','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'COMPACT FLOURESCENT LAMP (CFL) 18 watts '),
			array( 'stocknumber' => '03-025','entityname' => 'Polytechnic University of the Philippines','unit' => 'PACK','reorderpoint'=> '0','supplytype' => 'CARBON, SHORT, 100/BXS'),
			array( 'stocknumber' => '03-026','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '03-027','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'CLIP, BACKFOLD, 32MM(1 1/4)  ALL METAL, 12PCS/BOX'),
			array( 'stocknumber' => '03-028','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'CLIP, BACKFOLD, 50MM(2)  ALL METAL, 12PCS/BOX'),
			array( 'stocknumber' => '03-029','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CALCULATOR, 12 DIGITS, TWO WAY POWER '),
			array( 'stocknumber' => '03-030','entityname' => 'Polytechnic University of the Philippines','unit' => 'pcs','reorderpoint'=> '0','supplytype' => 'Calculator, Palm Size Printing, Canon'),
			array( 'stocknumber' => '03-031','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'CHAIR, monobloc, white, with backrest'),
			array( 'stocknumber' => '04-001','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '04-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'DVD, REWRITABLE '),
			array( 'stocknumber' => '04-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'DATA FOLDER, LONG '),
			array( 'stocknumber' => '04-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'DATING MACHINE, STAMP'),
			array( 'stocknumber' => '04-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'DRY SEAL, PUP SEAL'),
			array( 'stocknumber' => '04-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'CAN ','reorderpoint'=> '0','supplytype' => 'DISINFECTANT SPRAY, KILLS OF GERMS & VIRUSES'),
			array( 'stocknumber' => '05-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ENVELOPE DOCUMENTARY -GOLDEN KRAFT BROWN LONG 10" X 15"'),
			array( 'stocknumber' => '05-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ENVELOPE DOCUMENTARY SHORT 150 GSM 9" X 12"'),
			array( 'stocknumber' => '05-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ENVELOPE EXPANDING, LONG '),
			array( 'stocknumber' => '05-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ENVELOPE EXPANDING, SHORT '),
			array( 'stocknumber' => '05-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ENVELOPE, MAILING, WHITE 500/BX, SHORT'),
			array( 'stocknumber' => '05-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'ENVELOPE, MAILING, WHITE,  500/BX LONG '),
			array( 'stocknumber' => '05-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ERASER, BLACKBOARD'),
			array( 'stocknumber' => '05-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ERASER, RUBBER, RECTANGULAR, PLATON BRAND'),
			array( 'stocknumber' => '05-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'ENVELOPE, MAILING, WINDOW,  WHITE,  500/BX LONG '),
			array( 'stocknumber' => '05-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '06-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FACSIMILE INK FILM RECORDER NO. TTRP93'),
			array( 'stocknumber' => '06-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FAN, ORBIT  18”Ø  '),
			array( 'stocknumber' => '06-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FAN, STAND TYPE'),
			array( 'stocknumber' => '06-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FAN, TABLE TYPE'),
			array( 'stocknumber' => '06-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FAN, WALL TYPE'),
			array( 'stocknumber' => '06-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'FANCY FOLDER SHORT'),
			array( 'stocknumber' => '06-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'FASTENER, METAL'),
			array( 'stocknumber' => '06-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'FASTENER, PLASTIC PRINCE'),
			array( 'stocknumber' => '06-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLASH DRIVE 16GB, USB VERSION 2.0 PORT COMPATIBLE, PLUG AND PLAY APACER BRAND'),
			array( 'stocknumber' => '06-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLASH DRIVE 8GB, USB VERSION 2.0 PORT COMPATIBLE, PLUG AND PLAY APACER BRAND'),
			array( 'stocknumber' => '06-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LAMP TABULAR 16 WATTS'),
			array( 'stocknumber' => '06-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LAMP TABULAR 18 WATTS '),
			array( 'stocknumber' => '06-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LAMP TABULAR 36 WATTS'),
			array( 'stocknumber' => '06-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LAMP TABULAR 40 WATTS'),
			array( 'stocknumber' => '06-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LIGHTNING FIXTURE 1X40W'),
			array( 'stocknumber' => '06-016','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FOLDER LONG TAG BOARD 14 POINTS LEGAL SIZE'),
			array( 'stocknumber' => '06-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FOLDER SHORT TAG BOARD 14 POINTS LETTER SIZE                                    '),
			array( 'stocknumber' => '06-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LAMP, 28WATTS 25/BOX'),
			array( 'stocknumber' => '06-019','entityname' => 'Polytechnic University of the Philippines','unit' => 'pcs','reorderpoint'=> '0','supplytype' => 'FOLDER, PRESSBOARD , LEGAL PAPER BOARD.,100/PACK                     '),
			array( 'stocknumber' => '06-020','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FOLDER, PRESSBOARD , SHORT PAPER BOARD.,100/PACK                     '),
			array( 'stocknumber' => '06-021','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FOLDER, FANCY , LEGAL  SIZE PAPER DOC .,50/PACK                           '),
			array( 'stocknumber' => '06-022','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FOLDER,  TAGBOARD, A4 SIZE DOC., 100/PACK                 '),
			array( 'stocknumber' => '06-023','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FACSIMILE FILM (PANASONIC) KX-FP 342'),
			array( 'stocknumber' => '06-024','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'FLOURESCENT LAMP TABULAR 20 WATTS'),
			array( 'stocknumber' => '06-025','entityname' => 'Polytechnic University of the Philippines','unit' => 'Unit ','reorderpoint'=> '0','supplytype' => 'FAN, ORBIT  16”Ø  '),
			array( 'stocknumber' => '07-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'BTL','reorderpoint'=> '0','supplytype' => 'GLUE,  ALL PURPOSE IN JAR W/APPLICATOR 300 GRAMS'),
			array( 'stocknumber' => '08-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'HANDBOOK ON PHILIIPPINE GOVT. PROCUREMENT '),
			array( 'stocknumber' => '08-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'UNIT','reorderpoint'=> '0','supplytype' => 'HARD DRIVE, EXTERNAL, 70MM Between prongs'),
			array( 'stocknumber' => '09-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'INDEX CARD BOX, 4-3/8"x5-5/8" x 4"(3" x 5")'),
			array( 'stocknumber' => '09-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'INDEX CARD BOX, 5-3/8"x8-7/8" x 6"(5" x 8")'),
			array( 'stocknumber' => '09-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'BOX','reorderpoint'=> '0','supplytype' => 'INDEX TAB, SELF-ADHESIVE '),
			array( 'stocknumber' => '09-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE FOR HP 840/845 #C6625A (HP 17)COLORED'),
			array( 'stocknumber' => '09-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE FOR HP 840C/845 #C6615A(HP 15) BLACK'),
			array( 'stocknumber' => '09-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE FOR HP 840C/845 #C6615A(HP 22 ) colored '),
			array( 'stocknumber' => '09-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE, HP #21, BLACK '),
			array( 'stocknumber' => '09-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CART. FOR HP PRINTER, #1823, COLORED   HP23'),
			array( 'stocknumber' => '09-009','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE, HP #27, BLACK'),
			array( 'stocknumber' => '09-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK HP LASERJET HP #28, COLORED'),
			array( 'stocknumber' => '09-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE FOR HP 710C/830C #51645A BLACK HP 45'),
			array( 'stocknumber' => '09-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CART. FOR HP PRINTER 1220C C6578D ORIG. BRAND NEW COLORED HP78'),
			array( 'stocknumber' => '09-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE, BLACK  #38'),
			array( 'stocknumber' => '09-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE, COLORED  #39'),
			array( 'stocknumber' => '09-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE ,HP #60 BLACK '),
			array( 'stocknumber' => '09-016','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE, HP #60 COLORED'),
			array( 'stocknumber' => '09-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE HP #96, BLACK'),
			array( 'stocknumber' => '09-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP#97, COLORED'),
			array( 'stocknumber' => '09-019','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INKJET CARTRIDGE, HP #CD887AA (HP703)/D730/SERIES#736 BLACK'),
			array( 'stocknumber' => '09-020','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INKJET CARTRIDGE, HP #CD888AA (HP703)/D730/SERIES#735 COLORED'),
			array( 'stocknumber' => '09-021','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE, HP  #900 COLORED '),
			array( 'stocknumber' => '09-022','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE,  HP #900 BLACK'),
			array( 'stocknumber' => '09-023','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE HP #18, BLACK'),
			array( 'stocknumber' => '09-024','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP #18, CYAN'),
			array( 'stocknumber' => '09-025','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP #18, YELLOW'),
			array( 'stocknumber' => '09-026','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE HP  #18, MAGENTA'),
			array( 'stocknumber' => '09-027','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP #CD972AA (HP 920XL), CYAN '),
			array( 'stocknumber' => '09-028','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP #CD973AA (HP 920XL), MAGENTA '),
			array( 'stocknumber' => '09-029','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP #CD974AA (HP 920XL), YELLOW'),
			array( 'stocknumber' => '09-030','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET  CARTRIDGE  HP #CD975AA (HP 920XL), BLACK'),
			array( 'stocknumber' => '09-031','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK EPSON L110 (BLACK)'),
			array( 'stocknumber' => '09-032','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK EPSON L110 (CYAN)'),
			array( 'stocknumber' => '09-033','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK EPSON L110 (MAGENTA)'),
			array( 'stocknumber' => '09-034','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK EPSON L110 (YELLOW)'),
			array( 'stocknumber' => '09-035','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK COPYPRINTER, BLACK, GESTETNER MODEL 5307/5308/3440/5430, CPi7'),
			array( 'stocknumber' => '09-036','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK COPYPRINTER, BLACK, GESTETNER MODEL 5329, CP 12'),
			array( 'stocknumber' => '09-037','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '09-038','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET CARTRIDGE, HP704, BLACK'),
			array( 'stocknumber' => '09-039','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET CARTRIDGE,HP704, COLORED'),
			array( 'stocknumber' => '09-040','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INKJET CARTRIDGE, HP CC653 (901) BLACK, OFFICEJET 4580'),
			array( 'stocknumber' => '09-041','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK CART, HP CC656AA, (901) TRI-COLOR OFFICEJET 4500'),
			array( 'stocknumber' => '09-042','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK CART. OPSCAN 4U, 51604A'),
			array( 'stocknumber' => '09-043','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK DESKJET , CANNON FIXMA MX366 PG810 , BLACK'),
			array( 'stocknumber' => '09-044','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INK DESKJET , CANNON FIXMA MX366 PG811 , COLORED'),
			array( 'stocknumber' => '09-045','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INDEX CARD,3"x 5",ruled both sides, 500s/pack'),
			array( 'stocknumber' => '09-046','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'INDEX CARD, 5" x 8",ruled both side, 500s/pack'),
			array( 'stocknumber' => '09-047','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '09-048','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '09-049','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, BLACK'),
			array( 'stocknumber' => '09-050','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, CYAN'),
			array( 'stocknumber' => '09-051','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, MAGENTA'),
			array( 'stocknumber' => '09-052','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, ADVANTAGE HP 4625 #685, YELLOW'),
			array( 'stocknumber' => '09-053','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDIDGE, HP98'),
			array( 'stocknumber' => '09-054','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CANNON, #40'),
			array( 'stocknumber' => '09-055','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CANNON, #41'),
			array( 'stocknumber' => '09-056','entityname' => 'Polytechnic University of the Philippines','unit' => 'BTL','reorderpoint'=> '0','supplytype' => 'INK DUPLO DP514 '),
			array( 'stocknumber' => '09-057','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, GESTETNER DX2430, BLACK'),
			array( 'stocknumber' => '09-058','entityname' => 'Polytechnic University of the Philippines','unit' => 'CAN ','reorderpoint'=> '0','supplytype' => 'INSECTICIDE, MULTI INSECT KILLER, KILLS FLYING AND CRAWLING INSECTS'),
			array( 'stocknumber' => '09-059','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, HP 75, COLORED'),
			array( 'stocknumber' => '09-060','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGE, HP 74, BLACK'),
			array( 'stocknumber' => '09-061','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGEMP C1500 black'),
			array( 'stocknumber' => '09-062','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGEMP C1500 cyan'),
			array( 'stocknumber' => '09-063','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGEMP C1500 yellow'),
			array( 'stocknumber' => '09-064','entityname' => 'Polytechnic University of the Philippines','unit' => 'CART','reorderpoint'=> '0','supplytype' => 'INK CARTRIDGEMP C1500 Magenta'),
			array( 'stocknumber' => '09-065','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'INK JET HP 932, CL0575, BLACK '),
			array( 'stocknumber' => '09-066','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'INK JET HP 933, CN0585, CYAN '),
			array( 'stocknumber' => '09-067','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'INK JET HP 933, CN059S, MAGENMA'),
			array( 'stocknumber' => '09-068','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'INK JET HP 933, CL060S,YELLOW'),
			array( 'stocknumber' => '12-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'LOOSELEAF COVER W/ PAPER CLOTH STRAP, GREEN 8 1/2 X 14'),
			array( 'stocknumber' => '12-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'L-TYPE PLASTIC FOLDER'),
			array( 'stocknumber' => '13-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MAGAZINE FILE, LONG'),
			array( 'stocknumber' => '13-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MAGAZINE FILE, SHORT'),
			array( 'stocknumber' => '13-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKER, HIGHLIGHTER ASSORTED, NON TOXIC SMELL'),
			array( 'stocknumber' => '13-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKING PEN PERMANENT BLACK'),
			array( 'stocknumber' => '13-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKING PEN PERMANENT BLUE'),
			array( 'stocknumber' => '13-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKING PEN PERMANENT RED'),
			array( 'stocknumber' => '13-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKING PEN WHITEBOARD, BLACK'),
			array( 'stocknumber' => '13-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKING PEN WHITEBOARD, BLUE'),
			array( 'stocknumber' => '13-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MARKING PEN WHITEBOARD, RED'),
			array( 'stocknumber' => '13-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MASTER COPY PRINTER, CMPT17 MODEL 5307/5308 GESTETNER '),
			array( 'stocknumber' => '13-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MEDAL,GOLD (ORDINARY)'),
			array( 'stocknumber' => '13-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MOUSE. OPTICAL, USB CONNECTION TYPE, 400 DPI, PLUG AND PLAY: GENIUS NETSCROLL BRAND '),
			array( 'stocknumber' => '13-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MAGAZINE FILE W/ COVER, (cartile w/ operable cover holds up to A4 and Lega)'),
			array( 'stocknumber' => '13-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MEDAL, SIZE 4.5CM,  SILVER (HONOR STUDENT)'),
			array( 'stocknumber' => '13-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MEDAL, SIZE 4.5CM,  BRONZE (HONOR STUDENT)'),
			array( 'stocknumber' => '13-016','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MEDAL, SILVER (ORDINARY)'),
			array( 'stocknumber' => '13-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MEDAL,BRONZE (ORDINARY)'),
			array( 'stocknumber' => '13-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '13-019','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'MASTER COPY PRINTER, CMPT9 GESTETNER '),
			array( 'stocknumber' => '13-020','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '14-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'NOTEBOOK, STENOGRAPHIC, SPIRAL, 40 LEAVES'),
			array( 'stocknumber' => '14-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'NOTARIAL SEAL, NO. 24 SMALL BOX'),
			array( 'stocknumber' => '14-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PAD','reorderpoint'=> '0','supplytype' => 'NOTE PAD, STICK-ON (2"X3") 100 SHEETS PER PAD'),
			array( 'stocknumber' => '14-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PAD','reorderpoint'=> '0','supplytype' => 'NOTE PAD, STICK-ON (3"X3") 100 SHEETS PER PAD'),
			array( 'stocknumber' => '14-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PAD','reorderpoint'=> '0','supplytype' => 'NOTE PAD, STICK-ON (3"X4") 100 SHEETS PER PAD'),
			array( 'stocknumber' => '16-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS','reorderpoint'=> '0','supplytype' => 'PAPER BOND WHITE LONG, 70 GSM PG 8-1/2" X 13"'),
			array( 'stocknumber' => '16-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS','reorderpoint'=> '0','supplytype' => 'PAPER BOND WHITE SHORT, SUBS. 20 GOOD QUALITY'),
			array( 'stocknumber' => '16-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS','reorderpoint'=> '0','supplytype' => 'PAPER, MIMEO WHITE WOVE 70 GSM, LONG'),
			array( 'stocknumber' => '16-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS','reorderpoint'=> '0','supplytype' => 'PAPER, MIMEO WHITE WOVE 70 GSM, SHORT'),
			array( 'stocknumber' => '16-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS','reorderpoint'=> '0','supplytype' => 'PAPER, NEWSPRINT, PICOP LONG, 11x17"'),
			array( 'stocknumber' => '16-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'PAPER, MANILA '),
			array( 'stocknumber' => '16-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS','reorderpoint'=> '0','supplytype' => 'PAPER MIMEOGRAPH GROUNDWOOD , 216MM X 330MM, 60GSM '),
			array( 'stocknumber' => '16-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'PASTE, WATER WELL'),
			array( 'stocknumber' => '16-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'PENCIL LEAD W/ ERASER'),
			array( 'stocknumber' => '16-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'PENCIL SHARPENER'),
			array( 'stocknumber' => '16-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'PENCIL, MECHANICAL, 0.5 STEADLER'),
			array( 'stocknumber' => '16-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'PUNCHER'),
			array( 'stocknumber' => '16-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'PUSH PIN, FLAT HEAD TYPE , ASSORTED COLORS, 100PCS/CASE'),
			array( 'stocknumber' => '16-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'RMS.','reorderpoint'=> '0','supplytype' => 'PAPER BOND WHITE SHORT, SUBS. A4 GOOD QUALITY'),
			array( 'stocknumber' => '16-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'PAD','reorderpoint'=> '0','supplytype' => 'PAPER, RULED PAD, 216MMX330, 90 SHEETS/PAD'),
			array( 'stocknumber' => '16-016','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '16-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'Philippines Flag ,    3 ft x 6 ft. Standard'),
			array( 'stocknumber' => '16-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'Philippines Flag ,    Big Size'),
			array( 'stocknumber' => '16-021','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '18-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'RECORD BOOK , 300 PAGES'),
			array( 'stocknumber' => '18-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'RECORD BOOK , 500 PAGES'),
			array( 'stocknumber' => '18-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'SPOOL','reorderpoint'=> '0','supplytype' => 'RIBBON , MANUAL TYPEWRITER '),
			array( 'stocknumber' => '18-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'RIBBON FOR FAX  KX-FP701 (PANASONIC)'),
			array( 'stocknumber' => '18-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'RIBBON FOR PRINTER, EPSON LQ-2170/2180/2190 ORIGINAL                                 '),
			array( 'stocknumber' => '18-006','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '18-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'RIBBON LX-300/800 PRINTER EPSON ORIGINAL'),
			array( 'stocknumber' => '18-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'RUBBER BAND'),
			array( 'stocknumber' => '18-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RULER, 12"'),
			array( 'stocknumber' => '18-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RULER, 18"'),
			array( 'stocknumber' => '18-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RULER, 24"'),
			array( 'stocknumber' => '18-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RING BINDER, 12.7mm x 1.12m (1/2"x44"), plastic'),
			array( 'stocknumber' => '18-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RING BINDER, 19mm x 1.12m(3/4"x44"), plastic'),
			array( 'stocknumber' => '18-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RING BINDER, 25mm x 1.12m (1"x44"), plastic'),
			array( 'stocknumber' => '18-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'RING BINDER, 50mm x 1.12m(2" x 44"), plastic'),
			array( 'stocknumber' => '18-016','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'RIBBON FACSIMILE PANASONIC KX-FP342CX'),
			array( 'stocknumber' => '18-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'REGISTRATION CARD'),
			array( 'stocknumber' => '18-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'RIBBON, YMCKO full color, 250 prints/roll'),
			array( 'stocknumber' => '18-019','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'RIBBON, EPSON FX 100 #8755'),
			array( 'stocknumber' => '19-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'SCISSORS, 158MM MIN. LENGTH, SYMMETRICAL, JOY BRAND'),
			array( 'stocknumber' => '19-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'SHARPENER, PENCIL '),
			array( 'stocknumber' => '19-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'SIGNPEN, BLACK, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND'),
			array( 'stocknumber' => '19-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'SIGNPEN, BLUE, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND'),
			array( 'stocknumber' => '19-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'SIGNPEN, RED, LIQUID GEL INK, 0.5MM NEEDLE TIP, PENTEL ENERJEL BRAND'),
			array( 'stocknumber' => '19-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'STAMP PAD'),
			array( 'stocknumber' => '19-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'BTL','reorderpoint'=> '0','supplytype' => 'STAMP PAD, INK '),
			array( 'stocknumber' => '19-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'STAPLE WIRE, ACE                                                                '),
			array( 'stocknumber' => '19-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'STAPLE WIRE, REMOVER'),
			array( 'stocknumber' => '19-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'STAPLER, HEAVY DUTY'),
			array( 'stocknumber' => '19-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'STARTER, 40W 25/BOX'),
			array( 'stocknumber' => '19-012','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '19-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'STAPLER, BINDER TYPE HEAVY DUTY,  STAPLING, 12MM AND 17MM, CAP: 25-135 SHEETS OF 70GSM BOND PAPER'),
			array( 'stocknumber' => '19-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'STAPLE WIRE, 23/17'),
			array( 'stocknumber' => '19-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'pcs','reorderpoint'=> '0','supplytype' => 'STAPLE WIRE, REMOVER PLIER TYPE'),
			array( 'stocknumber' => '20-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE DISPENCER, HEAVY DUTY 25MM (1") WIDTH TRANS. TAPE '),
			array( 'stocknumber' => '20-002','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE MASKING 1" 24MM OLYMPIC'),
			array( 'stocknumber' => '20-003','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE MASKING 2" 48MM OLYMPIC'),
			array( 'stocknumber' => '20-004','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE, ADDING MACHINE  57M (2-1/4" WIDTH) 55GSM'),
			array( 'stocknumber' => '20-005','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE, ELECRICAL'),
			array( 'stocknumber' => '20-006','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE, PACKAGING, 1"'),
			array( 'stocknumber' => '20-007','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE, TRANSPARENT, 1"  24 MM ARMAK BRAND '),
			array( 'stocknumber' => '20-008','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE, TRANSPARENT, 2"  24 MM ARMAK BRAND '),
			array( 'stocknumber' => '20-009','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'THUMBTACK'),
			array( 'stocknumber' => '20-010','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TOILET, TISSUE PAPER, 2PLY SHEET/12RLS /PACK'),
			array( 'stocknumber' => '20-011','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CART. HP 05A , CE505A'),
			array( 'stocknumber' => '20-012','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CART. HP KONICA MINOLTA, BISHUB 210 TK-114'),
			array( 'stocknumber' => '20-013','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CART. HP P3010(HP55)'),
			array( 'stocknumber' => '20-014','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'TONER CART.HP OFFICEJET 7000'),
			array( 'stocknumber' => '20-015','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRDGE FOR HP LASER JET 1100/1100A C4092A BLACK'),
			array( 'stocknumber' => '20-016','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRDGE FOR HP LASER JET 85A (CE285AC) (P1102)'),
			array( 'stocknumber' => '20-017','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE FOR HP LASER JET 1200 C7115A BLACK'),
			array( 'stocknumber' => '20-018','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE FOR HP LASER JET 1300/13A'),
			array( 'stocknumber' => '20-019','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE FOR HP LASER JET 5/6L C3906A/F BLACK'),
			array( 'stocknumber' => '20-020','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE FOR HP LASER JET 53A  BLACK'),
			array( 'stocknumber' => '20-021','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP C9730A, black   '),
			array( 'stocknumber' => '20-022','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP C9731A, cyan   '),
			array( 'stocknumber' => '20-023','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP C9732A, yellow  '),
			array( 'stocknumber' => '20-024','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP C9733A, magenta  '),
			array( 'stocknumber' => '20-025','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP CB540A, black   HP125'),
			array( 'stocknumber' => '20-026','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP CB541A, cyan  HP125'),
			array( 'stocknumber' => '20-027','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP CB542A, yellow  HP125'),
			array( 'stocknumber' => '20-028','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP CB543A, magenta HP125'),
			array( 'stocknumber' => '20-029','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR  KYOCERA  KM-1620/TK-410'),
			array( 'stocknumber' => '20-030','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR  KYOCERA MITA, MODEL KM-2820 (TK-135)'),
			array( 'stocknumber' => '20-031','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '20-032','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR KYOCERA 220 (TK 439)'),
			array( 'stocknumber' => '20-033','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR KYOCERA LASER PRINTER MODEL FS-1030D (TK-120)'),
			array( 'stocknumber' => '20-034','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR KYOCERA LASER PRINTER MODEL FS-820/920(TK-110E) '),
			array( 'stocknumber' => '20-035','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR KYOCERA MITA DIGITAL COPIER MODEL KM-2530/3035'),
			array( 'stocknumber' => '20-036','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR KYOCERA MITA, MODEL KM-1820 (TK100)'),
			array( 'stocknumber' => '20-037','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER FOR KYOCERA, KM-2030'),
			array( 'stocknumber' => '20-038','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER GESTETNER, KONICA TN 101/KN 118'),
			array( 'stocknumber' => '20-039','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER HP LASERJET PRINT CARTRIDGE 3050/Q2612AC'),
			array( 'stocknumber' => '20-040','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER HP LASERJET PRINT CARTRIDGE 35A'),
			array( 'stocknumber' => '20-041','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'TONER GESTETNER DSM615/DSM618D 885474, 1500'),
			array( 'stocknumber' => '20-042','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER, KYOCERA TK70 9100/9500 SERIES 3050'),
			array( 'stocknumber' => '20-043','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '20-044','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'TONER, BROTHER DCP,  DN 7065 DR 225'),
			array( 'stocknumber' => '20-045','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS.','reorderpoint'=> '0','supplytype' => 'TONER, CARTRIDGE HP #C8543 (9040DN), BLACK'),
			array( 'stocknumber' => '20-046','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TAPE, PACKAGING, 2"'),
			array( 'stocknumber' => '20-047','entityname' => 'Polytechnic University of the Philippines','unit' => 'RLS','reorderpoint'=> '0','supplytype' => 'TWINE, PLASTIC, ONE KL. PER ROLL'),
			array( 'stocknumber' => '20-048','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, KYOCERA TK-1147'),
			array( 'stocknumber' => '20-049','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, COPIER KYOCERA FS-6525MFP  TK-479'),
			array( 'stocknumber' => '20-050','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, SHARP COPIER MACHINE AR-5520N, AR-021FT'),
			array( 'stocknumber' => '20-051','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, CART. HP 127FN, HP83A'),
			array( 'stocknumber' => '20-052','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, CARTIDGE MX-312FT, SHARP COPIER AR-5726'),
			array( 'stocknumber' => '20-053','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-23FTBA, BLACK'),
			array( 'stocknumber' => '20-054','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-23FTCA, CYAN'),
			array( 'stocknumber' => '20-055','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-23FTMA, MAGENTA'),
			array( 'stocknumber' => '20-056','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-23FTYA, YELLOW '),
			array( 'stocknumber' => '20-057','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, KYOCERA ECOSYS FS-1040, TK-1114'),
			array( 'stocknumber' => '20-058','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-45FTBA, BLACK'),
			array( 'stocknumber' => '20-059','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-27FTCA, CYAN'),
			array( 'stocknumber' => '20-060','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-27FTMA, MAGENTA'),
			array( 'stocknumber' => '20-061','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-27FTYA, YELLOW '),
			array( 'stocknumber' => '20-062','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS ','reorderpoint'=> '0','supplytype' => 'TONER, SHARP COPIER MACHINE AR-016 FT'),
			array( 'stocknumber' => '20-063','entityname' => 'Polytechnic University of the Philippines','unit' => '','reorderpoint'=> '0','supplytype' => 'N/A'),
			array( 'stocknumber' => '20-064','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-238FTI-3A, MODEL AR-6023N, BLACK'),
			array( 'stocknumber' => '20-065','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Black'),
			array( 'stocknumber' => '20-066','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Cyan'),
			array( 'stocknumber' => '20-067','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Magenta'),
			array( 'stocknumber' => '20-068','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, SAMSUNG CLP-Y 406S, Yellow '),
			array( 'stocknumber' => '20-069','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, HP 124A, BLACK'),
			array( 'stocknumber' => '20-070','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, KYOCERA, 1505/1510/1810'),
			array( 'stocknumber' => '20-071','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX 312 FT'),
			array( 'stocknumber' => '20-072','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-62FTBA, BLACK'),
			array( 'stocknumber' => '20-073','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-62FTCA, CYAN'),
			array( 'stocknumber' => '20-074','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-62FTYA, YELLOW'),
			array( 'stocknumber' => '20-075','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-62FTMA, MAGENTA'),
			array( 'stocknumber' => '20-076','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, MX-237FT'),
			array( 'stocknumber' => '20-077','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'TONER CARTRIDGE, LASERJET SAMSUNG, EXPRESS M2070W'),
			array( 'stocknumber' => '20-078','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'Toner Cartridge Brother TN 3030'),
			array( 'stocknumber' => '20-079','entityname' => 'Polytechnic University of the Philippines','unit' => 'cart.','reorderpoint'=> '0','supplytype' => 'Toner Cartridge Brother TN 3060'),
			array( 'stocknumber' => '21-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'BXS.','reorderpoint'=> '0','supplytype' => 'ULTRACARD PLAIN PVC, 500 PCS/BOX '),
			array( 'stocknumber' => '23-001','entityname' => 'Polytechnic University of the Philippines','unit' => 'PCS','reorderpoint'=> '0','supplytype' => 'WASTE BASKET, NON-RIGID PLASTIC, SQUARE, OVAL OR ROUND SHAPE, ASSORTED COLORS ')
		]);
	}
}
